# Generated by Django 4.2.7 on 2023-11-05 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("surname", models.TextField(verbose_name="Фамилия")),
                ("name", models.TextField(verbose_name="Имя")),
                ("middle_name", models.TextField(verbose_name="Отчество")),
                ("email", models.TextField(verbose_name="Почта")),
            ],
            options={
                "verbose_name": "Сотрудники",
                "verbose_name_plural": "Сотрудники",
                "db_table": "employee",
            },
        ),
        migrations.CreateModel(
            name="Employment_history",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "organisation",
                    models.TextField(verbose_name="Наименование организации"),
                ),
                ("reason", models.TextField(verbose_name="Причина увольнения")),
                ("position", models.TextField(verbose_name="Занимаемая должность")),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="orders_app.employee",
                        verbose_name="Идентификатор сотрудника",
                    ),
                ),
            ],
            options={
                "verbose_name": "История трудовой деятельности",
                "verbose_name_plural": "История трудовой деятельности",
                "db_table": "employment_history",
            },
        ),
        migrations.CreateModel(
            name="Dismissal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.TextField(verbose_name="Приказ")),
                ("date", models.TextField(verbose_name="Дата_увольнения")),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="orders_app.employee",
                        verbose_name="Идентификатор сотрудника",
                    ),
                ),
            ],
            options={
                "verbose_name": "Увольнение",
                "verbose_name_plural": "Увольнения",
                "db_table": "dismissal",
            },
        ),
        migrations.CreateModel(
            name="Business_trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.TextField(verbose_name="Город назначения")),
                ("days", models.TextField(verbose_name="Количество дней")),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="orders_app.employee",
                        verbose_name="Идентификатор сотрудника",
                    ),
                ),
            ],
            options={
                "verbose_name": "Командировка",
                "verbose_name_plural": "Командировки",
                "db_table": "business_trip",
            },
        ),
    ]
